title: Jiwoo Kum
description: Jiwoo Kum's academic homepage
url: "https://goldi1204.github.io"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "CV"
    link: "/Jiwoo_Kum_CV.pdf"
  - name: "NLP LAB"
    link: "https://sites.google.com/view/ssu-nlp/home"

footer: false
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Page design by Ankit Sultana"
